export default function Footer() {
  return (
    <footer className="border-t border-text-muted/10 py-6">
      <div className="mx-auto max-w-3xl px-4 text-center text-xs text-text-muted sm:px-6">
        <p>Study material is generated by AI and may contain inaccuracies — verify before exams.</p>
      </div>
    </footer>
  );
}
